# @package fixed

trainer_config:
  max_epochs: 10_000
  max_steps: 10_000

earlystop_config:

ood_dataset: ${fixed.dataset}

model_name: SSM
model_config:
  arch_name: fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.num_classes}
    hidden_dims: [100, 100, 100, 100, 100]

  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0
  clf_weight: 1.0
  n_classes: ${fixed.num_classes}
  n_particles: 1
  warmup_steps: 2500
  lr_step_size: 1000
