# @package fixed

trainer_config:
  max_steps: 10_000
  max_epochs: 10_000

earlystop_config:

ood_dataset: ${fixed.dataset}

model_name: VERA
model_config:
  arch_name: fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.num_classes}
    hidden_dims: [100, 100, 100, 100, 100]
    batch_norm: False
    slope: 0.2

  learning_rate: 0.001
  beta1: 0.0
  beta2: 0.9
  weight_decay: 0.0
  n_classes: ${fixed.num_classes}
  uncond: False
  gen_learning_rate: 0.001
  ebm_iters: 1
  generator_iters: 1
  entropy_weight: 0.0001

  generator_type: vera
  generator_arch_name: fc
  generator_config:
    noise_dim: 16
    post_lr: 0.00003
    init_post_logsigma: 0.1
  generator_arch_config:
    inp_dim: ${fixed.model_config.generator_config.noise_dim}
    num_classes: ${fixed.data_shape.0}
    hidden_dims: ${fixed.model_config.arch_config.hidden_dims}
    activation: relu
    batch_norm: True
    bias: False

  min_sigma: 0.01
  max_sigma: 0.3
  p_control: 0.0
  n_control: 0.0
  pg_control: 0.1
  clf_ent_weight: 0.0
  ebm_type: jem
  clf_weight: 1.0
  warmup_steps: 2500
  no_g_batch_norm: False
  batch_size: ${fixed.batch_size}
  lr_decay: 0.3
  lr_decay_epochs: [3000, 4000]
