# @package fixed

trainer_config:
  max_epochs: 50

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

model_name: Autoencoder
model_config:
  arch_name: wrn
  arch_config:
    depth: 10
    num_classes: 32
    widen_factor: 2
    input_channels: ${fixed.data_shape.2}
  decoder_arch_name: resnetgenerator
  decoder_arch_config:
    unit_interval: False
    feats: 32
    out_channels: ${fixed.data_shape.2}
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
