trainer_config:
  max_epochs: 20

checkpoint_config:
  monitor: val/acc
  mode: max
  save_last: True

earlystop_config:

ood_dataset: ${fixed.dataset}
sigma: 0.1

model_name: JEM
model_config:
  n_classes: 1
  arch_name: wrn
  arch_config:
    depth: 10
    num_classes: 1
    widen_factor: 2
    input_channels: ${fixed.data_shape.2}
    strides: [1, 2, 2]
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  smoothing: 0.0
  sgld_lr: 1.
  sgld_std: 0.01
  sgld_steps: 100
  pyxce: 0.0
  pxsgld: 1.0
  pxysgld: 0.0
  buffer_size: 10000
  reinit_freq: 0.05
  data_shape: ${fixed.data_shape}
  sgld_batch_size: ${fixed.batch_size}
  class_cond_p_x_sample: False
  entropy_reg_weight: 0.0001
