# @package _global_

slurm:
  experiments_per_job: 1
  sbatch_options:
    time: 0-30:00

fixed:
  trainer_config:
    max_epochs: 50

  checkpoint_config:
    monitor: val/ood
    mode: max

  dataset: cifar10
  num_classes: 10
  batch_size: 32
  data_shape: [32, 32, 3]

  test_ood_datasets:
    - lsun
    - textures
    - cifar100
    - svhn
    - celeb-a
    - uniform_noise
    - gaussian_noise
    - constant
    - svhn_unscaled

  model_config:
    ood_val_datasets:
      - celeb-a
      - cifar100
