# @package _global_

slurm:
  experiments_per_job: 5
  sbatch_options:
    time: 0-05:00

fixed:
  dataset: Gaussian2D
  num_classes: 3
  batch_size: 512
  data_shape:
    - 2

  model_config:
    is_toy_dataset: True

  test_ood_datasets:
    - AnomalousGaussian2D
